# Generated by Django 3.2.9 on 2021-11-26 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('today_time', models.TimeField()),
                ('today_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(help_text='Your age should be between 18 and 50', validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
